# Generated by Django 5.2.13 on 2026-04-22 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('ventas', 'Ventas'), ('operador', 'Operador')], default='operador', max_length=20),
        ),
    ]
