# Generated by Django 5.2.13 on 2026-04-26 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0004_nota'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nota',
            options={'ordering': ['-importante', '-fecha_actualizacion']},
        ),
    ]
